### ISSUE TITLE
Recomend you to put this token in private on .gitignore file.

### ISSUE THREAD

**Issue by onavascuez** [EthanHicks1/PaladinsDiscordCustomsBot#1]
https://github.com/EthanHicks1/PaladinsDiscordCustomsBot/blob/3790a42571e868dbc71f0f5d9742bcbe73bc9027/GenChamps.py#L11

**Comment by EthanHicks1** [comment]
Yeah, that would be a good idea. Thanks.

**Comment by EthanHicks1** [comment]
Regenerated token and place in an untracked file.
